#!/usr/bin/env bash
# JankyBorders - Dynamic Wallpaper Palette: Meadow Vista
borders \
    style=round \
    width=4.5 \
    hidpi=on \
    active_color='gradient(top_left=0xff38bdf8,bottom_right=0xff06b6d4)' \
    inactive_color=0x251e293b \
    background_color=0x200f172a
