#!/usr/bin/env bash
# Auto-generated by switch-wallpaper - DO NOT EDIT MANUALLY
export THEME_INDEX="1"
export THEME_SLUG="meadow"
export THEME_WALLHAVEN_ID="5y3571"
export THEME_NAME="Meadow Vista (Stefan Hansson)"
export THEME_WALLPAPER="/Users/aakashkulkarni/Pictures/Wallpapers/wallhaven-5y3571.jpg"
export THEME_HEX_ACCENT1="#38bdf8"
export THEME_HEX_ACCENT2="#06b6d4"
export THEME_ACCENT1="0xff38bdf8"
export THEME_ACCENT2="0xff06b6d4"
export THEME_TILE_BG="0xc21e2d36"
export THEME_TILE_BORDER="0x3874c7ec"
export THEME_ITEM_HIGHLIGHT="0x3538bdf8"
export THEME_CARD_BG="0xd818252d"
export THEME_CARD_BORDER="0x4538bdf8"
export THEME_BORDER_GRADIENT='gradient(top_left=0xff38bdf8,bottom_right=0xff06b6d4)'
export THEME_WS_BG="0x4038bdf8"
export THEME_WS_BORDER="0x8038bdf8"
