#!/usr/bin/env bash

# Source Colors
source "$HOME/.config/sketchybar/colors.sh"

# Global Bar Settings - Floating Hyprland Waybar Pill Style
sketchybar --bar \
  position=top \
  height=36 \
  blur_radius=30 \
  color="$BAR_COLOR" \
  border_color="$BAR_BORDER_COLOR" \
  border_width=1 \
  corner_radius=12 \
  margin=10 \
  y_offset=6 \
  padding_left=12 \
  padding_right=12

# Default item properties
sketchybar --default \
  icon.font="JetBrainsMono Nerd Font:Bold:14.0" \
  label.font="JetBrainsMono Nerd Font:Bold:13.0" \
  icon.color="$WHITE" \
  label.color="$WHITE" \
  background.height=26 \
  background.corner_radius=8 \
  background.padding_left=4 \
  background.padding_right=4

# ------------------------------------------------------------------------------
# Left: Workspaces (AeroSpace 1 to 5)
# ------------------------------------------------------------------------------
SPACE_ICONS=("1" "2" "3" "4" "5")

for i in "${!SPACE_ICONS[@]}"; do
  sid=$((i+1))
  sketchybar --add item space."$sid" left \
             --subscribe space."$sid" aerospace_workspace_change \
             --set space."$sid" \
                   icon="${SPACE_ICONS[i]}" \
                   icon.padding_left=8 \
                   icon.padding_right=8 \
                   background.color="$ITEM_BG_COLOR" \
                   background.drawing=off \
                   script="$HOME/.config/sketchybar/plugins/aerospace.sh $sid" \
                   click_script="aerospace workspace $sid"
done

# Separator
sketchybar --add item chevron left \
           --set chevron icon="" \
                         icon.color="$BLUE" \
                         icon.font="JetBrainsMono Nerd Font:Bold:11.0" \
                         icon.padding_left=6 \
                         icon.padding_right=6

# Active App Title
sketchybar --add item front_app left \
           --subscribe front_app front_app_switched \
           --set front_app \
                 icon.drawing=off \
                 label.color="$CYAN" \
                 script='sketchybar --set $NAME label="$INFO"'

# ------------------------------------------------------------------------------
# Right: Battery & Clock
# ------------------------------------------------------------------------------
sketchybar --add item clock right \
           --set clock update_freq=10 \
                       icon="󱑎" \
                       icon.color="$YELLOW" \
                       background.color="$ITEM_BG_COLOR" \
                       background.drawing=on \
                       script="$HOME/.config/sketchybar/plugins/clock.sh"

sketchybar --add item battery right \
           --subscribe battery power_source_change system_woke \
           --set battery update_freq=60 \
                         icon.color="$GREEN" \
                         background.color="$ITEM_BG_COLOR" \
                         background.drawing=on \
                         script="$HOME/.config/sketchybar/plugins/battery.sh"

sketchybar --update
